export const events = [
  {
    image: "/images/event1.png",
    title: "Next.js Conf 2025",
    slug: "nextjs-conf-2025",
    location: "San Francisco, CA, USA",
    date: "2025-12-10",
    time: "09:00 AM - 06:00 PM",
  },
  {
    image: "/images/event2.png",
    title: "Europe Hackathon Summit",
    slug: "europe-hackathon-summit",
    location: "Berlin, Germany",
    date: "2026-01-15",
    time: "10:00 AM - 08:00 PM",
  },
  {
    image: "/images/event3.png",
    title: "JS World Conference",
    slug: "js-world-conference",
    location: "Amsterdam, Netherlands",
    date: "2026-02-20",
    time: "08:30 AM - 05:30 PM",
  },
  {
    image: "/images/event4.png",
    title: "DevFest Global",
    slug: "devfest-global",
    location: "Online",
    date: "2025-12-05",
    time: "All Day",
  },
  {
    image: "/images/event5.png",
    title: "PyCon US 2026",
    slug: "pycon-us-2026",
    location: "Salt Lake City, UT, USA",
    date: "2026-04-22",
    time: "09:00 AM - 05:00 PM",
  },
  {
    image: "/images/event6.png",
    title: "React Summit 2026",
    slug: "react-summit-2026",
    location: "London, UK",
    date: "2026-03-10",
    time: "09:30 AM - 06:30 PM",
  },
];
